### PR TITLE
Add custom flowzone action to finalize staging releases

### PR DESCRIPTION
**Pull request by pipex**
Change-type: patch

### CODE REVIEW

**Comment by cywang117** [comment]
What was the method for finalizing before @pipex , or was there no finalization at all of staging with the last flowzone changes?

**Comment by pipex** [comment]
There wasn't one @cywang117, the last two PRs have not been finalized on staging

**Comment by cywang117** [comment]
Nice catch @pipex .

**Comment by pipex** [comment]
@balena-ci rebase

**Comment by pipex** [comment]
@balena-ci I self certify!

**Pull request merged**
