### PR TITLE
Log error responses from API when reporting state

### PR DESCRIPTION
**Pull request by pipex**
Change-type: patch
Relates-to: #1680

### CODE REVIEW

**Comment by pipex** [comment]
Drafting for the moment as we want to see if any filtering is required from API messages

**Comment by pipex** [comment]
Ok, taking of draft. Changed commit message to make it more specific, this is only when reporting state and doesn't include possible errors when getting target state or for streaming logs.

**Comment by cywang117** [comment]
Looks good. I have a thought -- if #1666 is merged before this, you could edit the test [here](https://github.com/balena-os/balena-supervisor/pull/1666/files#diff-515ffc947b31b73e1ec0e626bb17710db92281e29ff3e4c09f6376bd59317b4eR391-R412) to display statusMessages from the cloud if we wanna cover all our bases. Otherwise if this merges first (more likely), I'll rebase & add the test. Both are ok with me.

**Comment by pipex** [comment]
@balena-ci rebase

**Comment by pipex** [comment]
Can we get an approval here @cywang117 @20k-ultra 🙏🏻

**Review by 20k-ultra — APPROVED** [review]

**Pull request merged**
