### PR TITLE
Fix passing driver_opts from compose to docker network creation

### PR DESCRIPTION
**Pull request by quentingllmt**
Connects-to: https://github.com/balena-os/balena-supervisor/issues/1689
Change-Type: patch
Signed-off-by: quentinGllmt <quentin@quentingllmt.fr>

### CODE REVIEW

**Comment by pipex** [comment]
Hi Quentin, thanks for the PR! 

Would you mind adding some sample configurations on the [tests for this module](https://github.com/balena-os/balena-supervisor/blob/master/test/src/compose/network.spec.ts#L19)? That will allow us ensure that that config is being interpreted properly.

Thanks again!

**Comment by quentingllmt** [comment]
Hi @pipex,

I'm not really used to writing tests (furthermore for an app I know nothing of internally) but I did try anyway if it can help for a fast merge. I just hope those tests are what you are expecting. 
It seems to me you were not testing the `network.toDockerConfig()` output at all and that's where I made the modifications so I have added a new test case for that export which pretty much test everything. Hope that's OK !

**Comment by pipex** [comment]
That's a great catch @quentingllmt, nice work with the tests. I don't have any additional comments, I'll wait for my colleagues to take a second look and will approve

**Comment by pipex** [comment]
@balena-ci rebase

**Review by 20k-ultra — CHANGES_REQUESTED** [review]
Just to establish some terminology, the test suite is the **describe** block and a test case is the **it** blocks inside a suite. 

In your tests you've added a suite with a test which are great but my only request is that you move your test case "creates a valid network create options from the compose config" into the "creating a network from a compose object" test suite found on line 7. Then delete your test suite since it will be empty.

After that I think changing the test case name to "parses values from a compose object" is more clear for the case as well.

**Comment by quentingllmt** [comment]
@20k-ultra You're right. Done
When do you think this PR could be approved ?

**Review by 20k-ultra — APPROVED** [review]

**Comment by 20k-ultra** [comment]
Squash (fixup) all your commits into the first one then rebase master and force push with lease. I'm realizing our contribution docs do not contain these instructions so I've created a PR to help make this easier next time.

Check out exactly what I mean about squashing your history and rebasing master https://github.com/balena-os/balena-supervisor/pull/1697/commits/d3ddb4e2530fcf11b95dbdd4505ee95a0713c70d?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by quentingllmt** [comment]
@20k-ultra Done but versionbot failed.. Why ?

**Comment by cywang117** [comment]
@quentingllmt I believe this is because the `Change-type` footer is mis-capitalized as `Change-Type` instead. It's not as intuitive as we'd like, so I'll fix it, no worries. Thanks for this contribution!

**Comment by cywang117** [comment]
@balena-ci rebase

**Comment by cywang117** [comment]
@quentingllmt Looks like our ci is having some issues, would you mind:
- Changing any commit footers that use `Change-Type` to `Change-type`
- Rebasing on top of master
?

Thanks again!

**Comment by 20k-ultra** [comment]
@quentingllmt you have done a great job with our feedback and I'm so sorry for all the friction. Versionist is getting tripped up because your commit message contains the additional footers so it cannot find the Change-type.

Right now your commit is:

```
Fix parsing driver_opts from compose to docker network creation

Change-Type: patch
Signed-off-by: quentinGllmt <quentin@quentingllmt.fr>

network create config tests

test suite refactoring
```

But if you make it:

```
Fix parsing driver_opts from compose to docker network creation

Change-Type: patch
Signed-off-by: quentinGllmt <quentin@quentingllmt.fr>
```

then your PR will pass and merge

**Comment by quentingllmt** [comment]
@20k-ultra  Yes that's what I thought and I already did that in the last commit. It should be fine now!

**Comment by 20k-ultra** [comment]
thanks @quentingllmt! You can get this change running a device by upgraded to Supervisor v12.6.8 from the self service upgrade section of the dashboard. Test this on a development device first as these releases happen often and only rely on unit testing.

**Pull request merged**
