### PR TITLE
Fix poll interval

### PR DESCRIPTION
**Pull request by 20k-ultra**
docs were using the value which the API passed but the default is actually found in these 2 locations:

https://github.com/balena-os/balena-supervisor/blob/311f902df4a153b27d1524b454f8c6cba5fd33ad/src/config/schema-type.ts#L61-L64

https://github.com/balena-os/balena-supervisor/blob/311f902df4a153b27d1524b454f8c6cba5fd33ad/src/device-config.ts#L118-L122

### CODE REVIEW

**Comment by 20k-ultra** [comment]
@balena-ci rebase

**Comment by cywang117** [comment]
LGTM!

**Comment by 20k-ultra** [comment]
@balena-ci rebase

**Comment by 20k-ultra** [comment]
@balena-ci rebsae

**Comment by 20k-ultra** [comment]
@balena-ci rebase

**Comment by 20k-ultra** [comment]
@balena-ci I self-certify!

**Pull request merged**
