### PR TITLE
Simplify getting images for cleanup

### PR DESCRIPTION
**Pull request by cywang117**
`getImagesForCleanup` used to query the Engine for the Supervisor image, which is unnecessary given that the Supervisor has access to `constants.supervisorImage`. Thus, this Engine query is removed.

The method is simplified and made more clear, and
`imageManager.isCleanupNeeded` doesn't need to be stubbed in tests.

Change-type: patch
Signed-off-by: Christina Ying Wang <christina@balena.io>

### CODE REVIEW

**Review by pipex — COMMENTED** [review]
Great work @cywang117. LGTM when you are ready!

**Comment by cywang117** [comment]
@balena-ci rebase

**Comment by cywang117** [comment]
Ran some tests upgrading to this version, including on an older OS, v2.38 & v9.x Supervisor. Found that `image.RepoTags` can be falsey, so accounted for that in https://github.com/balena-os/balena-supervisor/commit/8174ea9643fb1059aad6fb05c68f42ade0579475 to prevent "RepoTags is not an iterator" errors. 

An observation about why an old Supervisor image may not be cleaned up: `constants.supervisorImage` is always passed to the Supervisor as an env var as SUPERVISOR_IMAGE, and this is equivalent to SUPERVISOR_IMAGE in `/etc/balena-supervisor/supervisor.conf` or `/tmp/update-supervisor.conf` currently. This interface is expected to change. As the image name is in the format `registry2.balena-cloud.com` with a unique hash after it per image, and older Supervisor images have a different unique hash, old Supervisor images may not be cleaned up (unless going through the official Supervisor self-serve upgrade process). 

The cleanup function was from a time when Supervisor images were tagged `balena/$ARCH-supervisor:$VERSION`, thus the cleanup works better when Supervisor images are tagged in that format.

In the future perhaps we can cleanup images by their labels instead of by their names, and Supervisor images can use a specific label.

**Comment by cywang117** [comment]
@balena-ci I self-certify!

**Pull request merged**
