### PR TITLE
Fix partition mounting for GPT partitioned disks

### PR DESCRIPTION
**Pull request by cywang117**
Closes: 2150
Change-type: patch

Invalidated 14.10.0 which didn't account for GPT-partitioned balenaOS images.

### CODE REVIEW

**Comment by cywang117** [comment]
This doesn't work as there's no access to `/dev/disk` in the Supervisor, continuing to investigate.

**Comment by cywang117** [comment]
Tested on:
- [x]aarch64
- [x] armv7hf
- [x] amd64 (legacy MBR)
- [ ] amd64 (GPT)
- [ ] rpi (armv6)

**Comment by pipex** [comment]
@jakogut because this supervisor needs to run on older OS versions where we cannot retroactively modify the start script to add the mounts

**Comment by jakogut** [comment]
@pipex That makes sense, thanks.

**Review by jakogut — COMMENTED** [review]
Looks good to me

**Comment by cywang117** [comment]
Testing meta-balena: https://github.com/balena-os/meta-balena/pull/3096

**Comment by cywang117** [comment]
@balena-ci I self-certify!

**Pull request merged**
