### PR TITLE
Add troubleshooting notice for macOS

### PR DESCRIPTION
**Pull request by fisehara**
When developing on macOS (Darwin) DBus may have to be installed.

Change-type: patch
Signed-off-by: fisehara <harald@balena.io>

### CODE REVIEW

**Comment by 20k-ultra** [comment]
You are running the Supervisor on a machine with OS X ? The normal development workflow is to livepush the Supervisor to a device running balenaOS so developing on the machine that also has the git repository is new to me. Even in that situation we run the Supervisor using docker in docker (run balenaOS inside docker)

**Comment by fisehara** [comment]
The npm install is failing when I have not installed the dbus package on macos.

**Comment by cywang117** [comment]
@fisehara We could probably make the docs section more generic by adding what libraries are needed for different OS's. I know I definitely encountered the `dbus-1 not found` error when first trying to set up the repo:
- Debian: `sudo apt-get install libdbus-1-dev`
- CentOS: `sudo yum install dbus-devel`
- Arch: Maybe @20k-ultra knows?
- MacOS: `brew install dbus`
- WSL: Same as Linux comands above, depends on distro installed

**Comment by 20k-ultra** [comment]
installing all these dependencies just to develop the Supervisor sucks...I dislike that just to get the types for software you'll never run you have to install it....I wonder if there's another way.

**Comment by pipex** [comment]
@balena-ci rebase

**Review by pipex — APPROVED** [review]

**Pull request merged**
