### PR TITLE
Convert device-api/common.js to TypeScript

### PR DESCRIPTION
**Pull request by cywang117**
I've removed the `serviceAction` function - it doesn't seem to be used anywhere. Let me know if I should revert this removal.

Change-type: patch
Closes: #1650
Signed-off-by: Christina Wang <christina@balena.io>

### CODE REVIEW

**Comment by 20k-ultra** [comment]
Let's consider just removing this file entirely rather then converting to TS. If we can make the code that uses it to talk to the application manager directly that would be the best. It already knows how to restart a service we may just need to add the purge but there is a [cleanup] step but it looks to just remove images ? which probably removes their containers and volumes...

**Comment by cywang117** [comment]
@20k-ultra See reference: https://github.com/balena-os/balena-supervisor/pull/1635#discussion_r605372192 a cleanup step never gets generated for `doPurge`. Also we want to keep images, just remove their containers & associated volumes, Perhaps if we want to combine `doPurge` into application manager we could create a new composition step, `purge`, that handles purge specifically?

**Comment by 20k-ultra** [comment]
Yup, creating a purge step is exactly what I meant. I was just mentioning that maybe the clean step may already do that but it didn't look like it since it was removing images.

**Comment by cywang117** [comment]
Great idea! I'll close this PR so we can rethink / work on this idea - I'll also create & link an issue.

**Pull request closed without merging**
