### PR TITLE
Bump contrato from 0.5.0 to 0.6.3

### PR DESCRIPTION
**Pull request by mehalter**
Change-type: patch

### CODE REVIEW

**Comment by mehalter** [comment]
@balena-ci rebase

**Comment by cywang117** [comment]
@mehalter Any big changes happen in contrato, or do the interfaces behave the same in the new version as the old version?

**Comment by mehalter** [comment]
The interfaces should behave the same. I looked at the 0.5 vs 0.6 release and there shouldn't be any breaking changes (I didn't do that release, so I'm not sure why they didn't do a patch release on 0.5 since the version is < 1.0). The main difference that I added was rewriting it in Typescript instead of javascript.

**Comment by cywang117** [comment]
@balena-ci rebase

**Pull request merged**
