### PR TITLE
backends: Add Jetson Orin NX custom device-tree support

### PR DESCRIPTION
**Pull request by acostach**
Change-type: patch

# Description

This PR enables custom device-tree loading support for the Jetson Orin NX device-type

# How Has This Been Tested?

This has been tested on the Orin NX device by setting the custom_fdt_file variable in /mnt/boot/extra_uEnv.txt , same as the SV sets it for the rest of the Jetson modules which support this feature.

### CODE REVIEW

**Comment by acostach** [comment]
It's not clear to me from the Flowzone logs if it's something in this commit that's causing the Publish balena/Publish custom checks to fail

**Comment by cywang117** [comment]
@acostach Sometimes the Supervisor integration tests time out in the builder, we've discussed looking at this but it's not clear the root cause. Usually re-running the failed checks causes them to pass 👍🏼

**Comment by acostach** [comment]
ack, thank you @cywang117 , otherwise the PR good to go?

**Review by cywang117 — APPROVED** [review]
LGTM!

**Pull request merged**
